apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    image: registry.redhat.io/amq7/amq-broker:7.7
  addressSettings:
    applyRule: replace_all
    addressSetting:
    - match: '#'
      deadLetterAddress: DLQ
    - match: 'abc#'
      deadLetterAddress: DLQABC
      defaultConsumerWindowSize: 2048000
      maxSizeBytes: '10m'
    - match: 'jms'
      deadLetterAddress: jmsdlq



