apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    image: registry.redhat.io/amq7/amq-broker:7.7
    resources:
      limits:
        cpu: 500m
        memory: 1024m
      requests:
        cpu: 250m
        memory: 512m

