apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    image: placeholder
  acceptors:
  - name: amqp
    protocols: amqp
    port: 5672
    sslEnabled: true
