apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-artemis-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: activemq-artemis-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: activemq-artemis-operator
    spec:
      containers:
      - args:
        # Explicitly set the logging level.
        # Valid values are debug, info, and error
        # from most to least.
        # If running entrypoint_debug then use '-- --zap-level debug'
        - '--zap-level debug'
        - '--zap-encoder console'
        command:
        - /home/activemq-artemis-operator/bin/entrypoint
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2130
          value: quay.io/artemiscloud/activemq-artemis-broker-init:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2150
          value: quay.io/artemiscloud/activemq-artemis-broker-init:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2160
          value: quay.io/artemiscloud/activemq-artemis-broker-init:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2130
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2150
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2160
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:dev.latest

        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2130_ppc64le
          value: quay.io/artemiscloud/activemq-artemis-broker-init:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2150_ppc64le
          value: quay.io/artemiscloud/activemq-artemis-broker-init:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2160_ppc64le
          value: quay.io/artemiscloud/activemq-artemis-broker-init:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2130_ppc64le
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes-openj9-11-rhel8:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2150_ppc64le
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes-openj9-11-rhel8:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2160_ppc64le
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes-openj9-11-rhel8:dev.latest

        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2130_s390x
          value: quay.io/artemiscloud/activemq-artemis-broker-init:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2150_s390x
          value: quay.io/artemiscloud/activemq-artemis-broker-init:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2160_s390x
          value: quay.io/artemiscloud/activemq-artemis-broker-init:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2130_s390x
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes-openj9-11-rhel8:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2150_s390x
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes-openj9-11-rhel8:dev.latest
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2160_s390x
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes-openj9-11-rhel8:dev.latest

#       image: registry-proxy.engineering.redhat.com/rh-osbs/amq7-amq-broker-rhel8-operator:dev.latest
        image: image-registry.openshift-image-registry.svc:5000/entmqbr-4413-4/activemq-artemis-operator:latest
        imagePullPolicy: Always
        name: activemq-artemis-operator
        resources: {}
      serviceAccountName: activemq-artemis-operator
