apiVersion: broker.amq.io/v2alpha1
kind: ActiveMQArtemis
metadata:
  name: example-activemqartemis
  application: example-activemqartemis-app
  labels:
    ActiveMQArtemis: example-activemqartemis
    application: example-activemqartemis-app
spec:
  deploymentPlan:
    size: 0
    image: registry.redhat.io/amq7/amq-broker:7.4
    #user: adminUser
    #password: adminPass
    role: admin
    requireLogin: true
    clustered: true
    #clusterUser: clusterUser
    #clusterPass: clusterPass
    persistenceEnabled: false
    journalType: nio
    messageMigration: false
