apiVersion: broker.amq.io/v2alpha1
kind: ActiveMQArtemis
metadata:
  name: example-activemqartemis
  application: example-activemqartemis-app
  labels:
    ActiveMQArtemis: example-activemqartemis
    application: example-activemqartemis-app
spec:
  deploymentPlan:
    size: 0
    image: docker-registry.default.svc:5000/entmqbr-2687-0/amq-broker-74-openshift:9.8
    #image: docker-registry.default.svc:5000/entmqbr-2687-0/amq-broker:7.4-5
    #image: registry.redhat.io/amq7/amq-broker:7.4
    #user: adminUser
    #password: adminPass
    role: admin
    requireLogin: false
    clustered: true
    clusterUser: clusteruser1
    clusterPassword: clusterpass1
    persistenceEnabled: true
    journalType: nio
    messageMigration: false
  acceptors:
    #- name: all-protocol
      #protocols: all
      #port: 61616
    - name: my
      protocols: amqp
      port: 5672
      sslEnabled: true
      #sslSecret: ym-secret
      expose: true
  connectors:
    - name: my-c
      host: localhost
      port: 22222
      sslEnabled: true
      #sslSecret: c-ym-secret
    #- name: second-c
      #host: 127.0.0.1
      #port: 33333
